In [2]:
from module_test2 import add

fatal: destination path 'Python-Regular-Expressions' already exists and is not an empty directory.


In [3]:
add(1,5)

6

In [4]:
import numpy as np

In [5]:
# 3차원 list형
list1=[[[1,2],[3,4]],[[5,6],[7,8]]]

In [6]:
arr=np.array(list1)
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
print(arr.size)
print(arr.ndim)
print(arr.shape)

8
3
(2, 2, 2)


In [8]:
lists=[]
for i in range(1,51):
    lists.append(i)
arr=np.array(lists)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [9]:
arr=np.arange(1,51,10) # 1이상
arr

array([ 1, 11, 21, 31, 41])

In [10]:
arr=np.random.rand(2,3) #0이상 1미만의 실수를 랜덤하게 뽑음 >> rand(행,열)
arr

array([[0.12484192, 0.02768243, 0.38869572],
       [0.41442339, 0.74857647, 0.35820939]])

In [11]:
arr=np.random.randint(2,10,(2,3)) #2이상 10미만의 정수를 랜덤하게 뽑음 >> randint(행,열)
arr

array([[6, 8, 9],
       [9, 8, 3]])

In [12]:
arr=np.random.randint(2,10) #2이상 10미만의 정수를 랜덤하게 뽑음 >> randint(행,열)
arr

5

In [13]:
arr_type=np.array([1.2,2.3,3.4,4.9999],dtype=np.int32) #정수 타입으로 출력
arr_type

array([1, 2, 3, 4])

In [14]:
arr_type=arr_type.astype("float64") #타입변경해주는 겁니다. 실수 타입으로 출력 . 큰따음표 필수입니다.
arr_type

array([1., 2., 3., 4.])

In [15]:
arr_a=np.array([1,2,3])
arr_a+arr_a

array([2, 4, 6])

In [16]:
arr_a*arr_a

array([1, 4, 9])

In [17]:
arr_b=np.array([4,5,6])

In [18]:
#2차원 배열
arr2_a=np.array([[1,2,3],
                [4,5,6]])

arr2_b=np.array([[7,8,9],
                [10,11,12]])

arr2_a+arr2_b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [19]:
arr2_a-arr2_b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [20]:
arr2_a*arr2_b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [21]:
arr2_a=np.array([[1,2,3],
                [4,5,6]])
arr2_a+3

array([[4, 5, 6],
       [7, 8, 9]])

In [22]:
arr_1=np.array([0,1,2,3,4,5])
arr_1[0]

0

In [23]:
arr_2=np.array([[1,2,3],[4,5,6]])
print(arr_2[0])

[1 2 3]


In [24]:
print(arr_2[0,0])

1


In [25]:
arr1=np.arange(10)
arr1[3:8]=12
arr1

array([ 0,  1,  2, 12, 12, 12, 12, 12,  8,  9])

In [26]:
arr2=np.arange(50).reshape(5,10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [27]:
arr2[:,0]

array([ 0, 10, 20, 30, 40])

In [28]:
arr2[:4,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [29]:
arr2[2,1]

21

In [30]:
score=np.array([80,75,55,96,30])
score

array([80, 75, 55, 96, 30])

In [31]:
score>=80    # score 배열에서 80이상에만 True, 아니면 False를 붙여서 Boolean형 원소들을 가진 배열을 추출.

array([ True, False, False,  True, False])

In [32]:
score[score>=80]  #위에 True, False, False,  True, False로 나와서 score에서 0번 3번째 원소만 출력

array([80, 96])

In [35]:
name=np.array(["영화","동원","성우","수민"])
name

array(['영화', '동원', '성우', '수민'], dtype='<U2')

In [36]:
bol=np.array([False,True,False,True])
name[bol]

array(['동원', '수민'], dtype='<U2')

In [37]:
name=="운비"  # 운비가 name 배열에 없어서 전부 False로 나오게 됨

array([False, False, False, False])

In [127]:
 name=="영화" # 영화가 name 배열에 0번째 인덱스에 있어서 0번째만 True로 나오게 됨 

array([ True, False, False, False])

In [123]:
score=np.array([[60,60],[70,70],[80,80],[90,90]])
score

array([[60, 60],
       [70, 70],
       [80, 80],
       [90, 90]])

In [128]:
score[ name=="영화"] #위에  True, False, False, False 로 나와 score의 0번째 원소출력

array([[60, 60]])

# Universally Function

In [629]:
arr=np.random.randint(1,10,size=(2,5))
arr

array([[5, 8, 1, 5, 3],
       [3, 6, 7, 5, 4]])

In [632]:
print(np.sum(arr))  # arr에 있는 모든 원소의 합 >> arr.sum()에 소괄호 있어야 됨.

47


In [633]:
print(arr.sum()) #이렇게 해도 결과는 마찬가지

47


In [634]:
print(np.mean(arr)) 
print(arr.mean())   # arr에 있는 모든 원소의 평균 >> arr.mean()에 소괄호 있어야 됨.

4.7
4.7


In [636]:
arr=np.arange(1,6)  
np.sqrt(arr)     # sqrt=squared root // arr의 각 원소에 대하여 root를 씌우고, 배열 출력

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [641]:
arr=np.array([-1,2,-3,4,-5])
np.abs(arr)   #abs=절대값 구하기 // arr의 각 원소에 대하여 절댓값으로 변환한 다음, 배열 반환

array([1, 2, 3, 4, 5])

In [644]:
arr2=np.arange(0,20).reshape(2,10)
arr2[:,1]

array([ 1, 11])

# 예제 - 성적 처리하기

In [653]:
students=["A","B","C"]
mid=[10,20,30]
final=[70,80,100]
total=mid+final # 연산이 아닌, 단지 원소를 추가해 주는 것 뿐임
total

[10, 20, 30, 70, 80, 100]

In [655]:
mid_score=np.array(mid)  #mid와 final은 list입니다.
final_score=np.array(final)
total=mid_score+final_score #numpy로 바꿔주니, 드디어 더하기 연산을 하게됨.
print(total) 

[ 80 100 130]


- 0에서부터 9까지 정수값을 가지는 array_a를 넘파이를 이용하여 출력해라

In [662]:
array_a=np.arange(0,10)
array_a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [659]:
array_b=np.array([i for i in range(0,10)])
array_b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [660]:
array_c=np.arange(0,10,2) # 0 이상 10 미만의 정수 값에서 짝수를 가지는 ndarray객체 만들기 
array_c

array([0, 2, 4, 6, 8])

In [666]:
#array_c의 shape.ndim.dtype.size를 출력
print(array_c.shape)
print(array_c.ndim)
print(array_c.dtype)
print(array_c.size)

(5,)
1
int32
5


In [669]:
#회사 매출이 올라서 전 직원의 월급을 100만원씩 올려줌
#현재 5명 직원 월급 : 220,250,230,300,200

salarys=np.array([220,250,230,300,200])
print(salarys+300)
print(salarys*2)

[520 550 530 600 500]
[440 500 460 600 400]


In [670]:
matrix_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [675]:
matrix_array3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(matrix_array3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [5]:
players=[[170,76.4],[183,86.2],[181,78.5],[176,80.1]]
play_arr=np.array(players)
# 선수들 중에서 몸무게 80이상인 사람만
play_arr[ : , 1]>=80

array([False,  True, False,  True])

In [683]:
play80kg=play_arr[play_arr[ : , 1]>=80]
play80kg

array([[183. ,  86.2],
       [176. ,  80.1]])

In [685]:
play180cm=play_arr[play_arr[ : , 0]>=180]
play180cm            

array([[183. ,  86.2],
       [181. ,  78.5]])

In [14]:
#(총 30개월) 30개의 원소를 가진 list  >> 엔화 단위의 금액들의 집합
revenue_in_ven=[110000,360000,440000,140000,180000,300000,340000,320000,360000,440000,140000,180000,300000,340000,320000,360000,440000,140000,180000,340000,330000,290000,280000,380000,170000,140000,230000,390000,400000,350000]
# 이 list를, numpy를 이용하여 엔화에서 원화로 바꾸기       >>   1엔=9.76원  
yen_revenue_array=np.array(revenue_in_ven)
won_revenue_array=yen_revenue_array*9.76
won_revenue_array

array([1073600., 3513600., 4294400., 1366400., 1756800., 2928000.,
       3318400., 3123200., 3513600., 4294400., 1366400., 1756800.,
       2928000., 3318400., 3123200., 3513600., 4294400., 1366400.,
       1756800., 3318400., 3220800., 2830400., 2732800., 3708800.,
       1659200., 1366400., 2244800., 3806400., 3904000., 3416000.])

In [15]:
#(총 30개월) 30개의 원소를 가진 list  >> 달러 단위의 금액들의 집합
revenue_in_dollar=[1200,1300,1600,1400,1500,1900,2100,2900,2800,2500,1200,1300,1600,1400,1500,1900,2100,2900,2800,2500,1200,1300,1600,1400,1500,1900,2100,2900,2800,2500]
# 이 list를, numpy를 이용하여 달러에서 원화로 바꾸기       >>   1달러=1301원 
dollar_array=np.array(revenue_in_dollar)
won_array=dollar_array*1301
won_array

array([1561200, 1691300, 2081600, 1821400, 1951500, 2471900, 2732100,
       3772900, 3642800, 3252500, 1561200, 1691300, 2081600, 1821400,
       1951500, 2471900, 2732100, 3772900, 3642800, 3252500, 1561200,
       1691300, 2081600, 1821400, 1951500, 2471900, 2732100, 3772900,
       3642800, 3252500])

In [16]:
# 엔화를 원화로 바꾼 array인 won_revenue_array과 
# 달러를 원화로 바꾼 won_array를 사용해 매 달 총 매출을 원화로 보고
total_array=won_revenue_array+won_array
total_array

array([2634800., 5204900., 6376000., 3187800., 3708300., 5399900.,
       6050500., 6896100., 7156400., 7546900., 2927600., 3448100.,
       5009600., 5139800., 5074700., 5985500., 7026500., 5139300.,
       5399600., 6570900., 4782000., 4521700., 4814400., 5530200.,
       3610700., 3838300., 4976900., 7579300., 7546800., 6668500.])

In [23]:
#20만엔 이하의 매출이 단긴 numpy array를 출력.
bad_days_revenue=yen_revenue_array[yen_revenue_array<=200000]
bad_days_revenue

array([110000, 140000, 180000, 140000, 180000, 140000, 180000, 170000,
       140000])

In [35]:
array_1=np.array([14,6,13,21,23,31,9,5])
print("최댓값 : "+str(array_1.max()))
print("최솟값 : "+str(array_1.min()))
print("중앙값 : "+str(np.median(array_1)))
print("표준편차 : "+str(array_1.std()))
print("분산 : "+str(array_1.var()))
print("각 절댓값 : "+str(np.abs(array_1)))
#최댓값 구하기 : max
#최솟값 : min
#중앙값 : median
#표준편차 : std
#분산 :var

최댓값 : 31
최솟값 : 5
중앙값 : 13.5
표준편차 : 8.496322733983215
분산 : 72.1875
각 절댓값 : [14  6 13 21 23 31  9  5]
