In [1]:
import numpy as np

In [3]:
x=np.random.randn(3,4)
x
# 표준정규분포로부터 발생한 난수 3 x 4개 만들어서 3행 4열의 array형태로 출력

array([[-0.0800234 ,  0.1693592 ,  1.70583813,  0.60923115],
       [ 0.44627519,  0.77003451, -0.09015255, -1.65040663],
       [-0.20784496,  0.06775839,  0.66439436, -1.48821024]])

In [4]:
y=np.corrcoef(x)
y
# 1행과 1행간 상관계수 // 1행과 2행간 상관계수 // 1행과 3행간 상관계수
# 2행과 1행간 상관계수 // 2행과 2행간 상관계수 // 2행과 3행간 상관계수
# 3행과 1행간 상관계수 // 3행과 2행간 상관계수 // 3행과 3행간 상관계수

array([[ 1.        , -0.29476064,  0.38792833],
       [-0.29476064,  1.        ,  0.76283631],
       [ 0.38792833,  0.76283631,  1.        ]])

In [8]:
print(np.std(x,0,ddof=1))
# np.std의 두번째 인수에 0 즉, 열을 따라 표준편차를 계산하였음.
# 자유도가 n - 1 (ddof = 1로 하였으므로)이라는 점을 고려하여 표준편차 계산
print(np.std(x,1))
# 표준편차 계산 두번째 인수에 1 즉, 행을 따라 표준편차를 계산하였음.

[0.34669914 0.37954475 0.9018064  1.2603922 ]
[0.68389357 0.92943193 0.78608258]


In [9]:
def d_mean(v):
    means=sum(v)/len(v)
    return [i-means for i in v]
# v안의 각 요소에 대하여 편차를 계산하여 리스트 형태로 반환

def dot(v,w):
    return sum(v_i * w_i for v_i,w_i in zip(v,w))
# v, w 리스트(벡터)에 대하여 내적을 반환

def sum_of_square(v):
    return dot(v,v)
# v 안의 각 요소들에 대하여 제곱합을 반환

def variance(v):
    return sum_of_square(d_mean(v))/len(v)
# v 안의 요소들에 대하여 분산을 계산

import math  

def stand_deviation(v):
    return math.sqrt(variance(v))
# v 안의 요소들에 대하여 표준편차를 계산

def covariance (v,w):
    return dot(d_mean(v),d_mean(w))/len(v)  
# 벡터 v와 w에 대하여 공분산을 계산

In [10]:
print(covariance (x[0],x[1]))
print(covariance (x[2],x[1]))
print(covariance (x[0],x[2]))

-0.1873594458235168
0.557336024886465
0.20854903813674366


## 조건부 확률 구하기 
- 두 명의 자식 중, 적어도 한 명이상이 오전에 태어난 딸일 때, 둘 다 딸일 조건부 확률 구하기

In [12]:
import random
def random_kid():
    return [random.choice(["오전","오후"]),random.choice(["남자","여자"])]

event1,event2=0,0 # event1은 둘 중 한명 이상이 오전에 태어난 딸인 사건, event2는 둘다 딸이고 event1을 만족하는 사건.

for _ in range(10000):
    younger=random_kid()
    older=random_kid() 
    if (younger[0]=='오전'and younger[1]=='여자') or (older[0]=='오전'and older[1]=='여자'):
        event1+=1
        if younger[1]=='여자' and older[1]=='여자':
            event2+=1

print(event1)
print(event2)
print(event2/event1)

4481
1922
0.42892211559919663


In [13]:
# 병에 걸릴 확률 : 0.001 >> 0.1 %
def random_disease():
    if random.choice(range(1000))==0: return "disease"
    else: return "healthy"

# 진단을 잘 못 했을 확률 : 0.01 >> 1 %    
def random_test():
    if random.choice(range(100))==0: return "wrong"
    else: return "right"

pos_and_disease=0
pos_and_NoDisease=0

for _ in range(100000):
    dis=random_disease()
    tes=random_test()
    if dis=="disease" and tes=="right":
        pos_and_disease+=1
    elif dis=="healthy" and tes=="wrong":
        pos_and_NoDisease+=1

# 양성 판정 받았을 때, 그 사람이 실제로 병에 걸려있을 확률
PDT=pos_and_disease/(pos_and_disease+pos_and_NoDisease)
print(PDT)

0.09034543844109831
